// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"happ/ent/event"
	"happ/ent/eventremindernotification"
	"happ/ent/predicate"
	"happ/ent/user"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// EventReminderNotificationQuery is the builder for querying EventReminderNotification entities.
type EventReminderNotificationQuery struct {
	config
	ctx        *QueryContext
	order      []eventremindernotification.OrderOption
	inters     []Interceptor
	predicates []predicate.EventReminderNotification
	withEvent  *EventQuery
	withUser   *UserQuery
	modifiers  []func(*sql.Selector)
	loadTotal  []func(context.Context, []*EventReminderNotification) error
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the EventReminderNotificationQuery builder.
func (ernq *EventReminderNotificationQuery) Where(ps ...predicate.EventReminderNotification) *EventReminderNotificationQuery {
	ernq.predicates = append(ernq.predicates, ps...)
	return ernq
}

// Limit the number of records to be returned by this query.
func (ernq *EventReminderNotificationQuery) Limit(limit int) *EventReminderNotificationQuery {
	ernq.ctx.Limit = &limit
	return ernq
}

// Offset to start from.
func (ernq *EventReminderNotificationQuery) Offset(offset int) *EventReminderNotificationQuery {
	ernq.ctx.Offset = &offset
	return ernq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (ernq *EventReminderNotificationQuery) Unique(unique bool) *EventReminderNotificationQuery {
	ernq.ctx.Unique = &unique
	return ernq
}

// Order specifies how the records should be ordered.
func (ernq *EventReminderNotificationQuery) Order(o ...eventremindernotification.OrderOption) *EventReminderNotificationQuery {
	ernq.order = append(ernq.order, o...)
	return ernq
}

// QueryEvent chains the current query on the "event" edge.
func (ernq *EventReminderNotificationQuery) QueryEvent() *EventQuery {
	query := (&EventClient{config: ernq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := ernq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := ernq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(eventremindernotification.Table, eventremindernotification.FieldID, selector),
			sqlgraph.To(event.Table, event.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, eventremindernotification.EventTable, eventremindernotification.EventColumn),
		)
		fromU = sqlgraph.SetNeighbors(ernq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryUser chains the current query on the "user" edge.
func (ernq *EventReminderNotificationQuery) QueryUser() *UserQuery {
	query := (&UserClient{config: ernq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := ernq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := ernq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(eventremindernotification.Table, eventremindernotification.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, eventremindernotification.UserTable, eventremindernotification.UserColumn),
		)
		fromU = sqlgraph.SetNeighbors(ernq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first EventReminderNotification entity from the query.
// Returns a *NotFoundError when no EventReminderNotification was found.
func (ernq *EventReminderNotificationQuery) First(ctx context.Context) (*EventReminderNotification, error) {
	nodes, err := ernq.Limit(1).All(setContextOp(ctx, ernq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{eventremindernotification.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (ernq *EventReminderNotificationQuery) FirstX(ctx context.Context) *EventReminderNotification {
	node, err := ernq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first EventReminderNotification ID from the query.
// Returns a *NotFoundError when no EventReminderNotification ID was found.
func (ernq *EventReminderNotificationQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = ernq.Limit(1).IDs(setContextOp(ctx, ernq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{eventremindernotification.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (ernq *EventReminderNotificationQuery) FirstIDX(ctx context.Context) int {
	id, err := ernq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single EventReminderNotification entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one EventReminderNotification entity is found.
// Returns a *NotFoundError when no EventReminderNotification entities are found.
func (ernq *EventReminderNotificationQuery) Only(ctx context.Context) (*EventReminderNotification, error) {
	nodes, err := ernq.Limit(2).All(setContextOp(ctx, ernq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{eventremindernotification.Label}
	default:
		return nil, &NotSingularError{eventremindernotification.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (ernq *EventReminderNotificationQuery) OnlyX(ctx context.Context) *EventReminderNotification {
	node, err := ernq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only EventReminderNotification ID in the query.
// Returns a *NotSingularError when more than one EventReminderNotification ID is found.
// Returns a *NotFoundError when no entities are found.
func (ernq *EventReminderNotificationQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = ernq.Limit(2).IDs(setContextOp(ctx, ernq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{eventremindernotification.Label}
	default:
		err = &NotSingularError{eventremindernotification.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (ernq *EventReminderNotificationQuery) OnlyIDX(ctx context.Context) int {
	id, err := ernq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of EventReminderNotifications.
func (ernq *EventReminderNotificationQuery) All(ctx context.Context) ([]*EventReminderNotification, error) {
	ctx = setContextOp(ctx, ernq.ctx, "All")
	if err := ernq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*EventReminderNotification, *EventReminderNotificationQuery]()
	return withInterceptors[[]*EventReminderNotification](ctx, ernq, qr, ernq.inters)
}

// AllX is like All, but panics if an error occurs.
func (ernq *EventReminderNotificationQuery) AllX(ctx context.Context) []*EventReminderNotification {
	nodes, err := ernq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of EventReminderNotification IDs.
func (ernq *EventReminderNotificationQuery) IDs(ctx context.Context) (ids []int, err error) {
	if ernq.ctx.Unique == nil && ernq.path != nil {
		ernq.Unique(true)
	}
	ctx = setContextOp(ctx, ernq.ctx, "IDs")
	if err = ernq.Select(eventremindernotification.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (ernq *EventReminderNotificationQuery) IDsX(ctx context.Context) []int {
	ids, err := ernq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (ernq *EventReminderNotificationQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, ernq.ctx, "Count")
	if err := ernq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, ernq, querierCount[*EventReminderNotificationQuery](), ernq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (ernq *EventReminderNotificationQuery) CountX(ctx context.Context) int {
	count, err := ernq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (ernq *EventReminderNotificationQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, ernq.ctx, "Exist")
	switch _, err := ernq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (ernq *EventReminderNotificationQuery) ExistX(ctx context.Context) bool {
	exist, err := ernq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the EventReminderNotificationQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (ernq *EventReminderNotificationQuery) Clone() *EventReminderNotificationQuery {
	if ernq == nil {
		return nil
	}
	return &EventReminderNotificationQuery{
		config:     ernq.config,
		ctx:        ernq.ctx.Clone(),
		order:      append([]eventremindernotification.OrderOption{}, ernq.order...),
		inters:     append([]Interceptor{}, ernq.inters...),
		predicates: append([]predicate.EventReminderNotification{}, ernq.predicates...),
		withEvent:  ernq.withEvent.Clone(),
		withUser:   ernq.withUser.Clone(),
		// clone intermediate query.
		sql:  ernq.sql.Clone(),
		path: ernq.path,
	}
}

// WithEvent tells the query-builder to eager-load the nodes that are connected to
// the "event" edge. The optional arguments are used to configure the query builder of the edge.
func (ernq *EventReminderNotificationQuery) WithEvent(opts ...func(*EventQuery)) *EventReminderNotificationQuery {
	query := (&EventClient{config: ernq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	ernq.withEvent = query
	return ernq
}

// WithUser tells the query-builder to eager-load the nodes that are connected to
// the "user" edge. The optional arguments are used to configure the query builder of the edge.
func (ernq *EventReminderNotificationQuery) WithUser(opts ...func(*UserQuery)) *EventReminderNotificationQuery {
	query := (&UserClient{config: ernq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	ernq.withUser = query
	return ernq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		EventID int `json:"event_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.EventReminderNotification.Query().
//		GroupBy(eventremindernotification.FieldEventID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (ernq *EventReminderNotificationQuery) GroupBy(field string, fields ...string) *EventReminderNotificationGroupBy {
	ernq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &EventReminderNotificationGroupBy{build: ernq}
	grbuild.flds = &ernq.ctx.Fields
	grbuild.label = eventremindernotification.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		EventID int `json:"event_id,omitempty"`
//	}
//
//	client.EventReminderNotification.Query().
//		Select(eventremindernotification.FieldEventID).
//		Scan(ctx, &v)
//
func (ernq *EventReminderNotificationQuery) Select(fields ...string) *EventReminderNotificationSelect {
	ernq.ctx.Fields = append(ernq.ctx.Fields, fields...)
	sbuild := &EventReminderNotificationSelect{EventReminderNotificationQuery: ernq}
	sbuild.label = eventremindernotification.Label
	sbuild.flds, sbuild.scan = &ernq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a EventReminderNotificationSelect configured with the given aggregations.
func (ernq *EventReminderNotificationQuery) Aggregate(fns ...AggregateFunc) *EventReminderNotificationSelect {
	return ernq.Select().Aggregate(fns...)
}

func (ernq *EventReminderNotificationQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range ernq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, ernq); err != nil {
				return err
			}
		}
	}
	for _, f := range ernq.ctx.Fields {
		if !eventremindernotification.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if ernq.path != nil {
		prev, err := ernq.path(ctx)
		if err != nil {
			return err
		}
		ernq.sql = prev
	}
	return nil
}

func (ernq *EventReminderNotificationQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*EventReminderNotification, error) {
	var (
		nodes       = []*EventReminderNotification{}
		_spec       = ernq.querySpec()
		loadedTypes = [2]bool{
			ernq.withEvent != nil,
			ernq.withUser != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*EventReminderNotification).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &EventReminderNotification{config: ernq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(ernq.modifiers) > 0 {
		_spec.Modifiers = ernq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, ernq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := ernq.withEvent; query != nil {
		if err := ernq.loadEvent(ctx, query, nodes, nil,
			func(n *EventReminderNotification, e *Event) { n.Edges.Event = e }); err != nil {
			return nil, err
		}
	}
	if query := ernq.withUser; query != nil {
		if err := ernq.loadUser(ctx, query, nodes, nil,
			func(n *EventReminderNotification, e *User) { n.Edges.User = e }); err != nil {
			return nil, err
		}
	}
	for i := range ernq.loadTotal {
		if err := ernq.loadTotal[i](ctx, nodes); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (ernq *EventReminderNotificationQuery) loadEvent(ctx context.Context, query *EventQuery, nodes []*EventReminderNotification, init func(*EventReminderNotification), assign func(*EventReminderNotification, *Event)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*EventReminderNotification)
	for i := range nodes {
		fk := nodes[i].EventID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(event.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "event_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (ernq *EventReminderNotificationQuery) loadUser(ctx context.Context, query *UserQuery, nodes []*EventReminderNotification, init func(*EventReminderNotification), assign func(*EventReminderNotification, *User)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*EventReminderNotification)
	for i := range nodes {
		fk := nodes[i].UserID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "user_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (ernq *EventReminderNotificationQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := ernq.querySpec()
	if len(ernq.modifiers) > 0 {
		_spec.Modifiers = ernq.modifiers
	}
	_spec.Node.Columns = ernq.ctx.Fields
	if len(ernq.ctx.Fields) > 0 {
		_spec.Unique = ernq.ctx.Unique != nil && *ernq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, ernq.driver, _spec)
}

func (ernq *EventReminderNotificationQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(eventremindernotification.Table, eventremindernotification.Columns, sqlgraph.NewFieldSpec(eventremindernotification.FieldID, field.TypeInt))
	_spec.From = ernq.sql
	if unique := ernq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if ernq.path != nil {
		_spec.Unique = true
	}
	if fields := ernq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, eventremindernotification.FieldID)
		for i := range fields {
			if fields[i] != eventremindernotification.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if ernq.withEvent != nil {
			_spec.Node.AddColumnOnce(eventremindernotification.FieldEventID)
		}
		if ernq.withUser != nil {
			_spec.Node.AddColumnOnce(eventremindernotification.FieldUserID)
		}
	}
	if ps := ernq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := ernq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := ernq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := ernq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (ernq *EventReminderNotificationQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(ernq.driver.Dialect())
	t1 := builder.Table(eventremindernotification.Table)
	columns := ernq.ctx.Fields
	if len(columns) == 0 {
		columns = eventremindernotification.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if ernq.sql != nil {
		selector = ernq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if ernq.ctx.Unique != nil && *ernq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range ernq.predicates {
		p(selector)
	}
	for _, p := range ernq.order {
		p(selector)
	}
	if offset := ernq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := ernq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// EventReminderNotificationGroupBy is the group-by builder for EventReminderNotification entities.
type EventReminderNotificationGroupBy struct {
	selector
	build *EventReminderNotificationQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (erngb *EventReminderNotificationGroupBy) Aggregate(fns ...AggregateFunc) *EventReminderNotificationGroupBy {
	erngb.fns = append(erngb.fns, fns...)
	return erngb
}

// Scan applies the selector query and scans the result into the given value.
func (erngb *EventReminderNotificationGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, erngb.build.ctx, "GroupBy")
	if err := erngb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*EventReminderNotificationQuery, *EventReminderNotificationGroupBy](ctx, erngb.build, erngb, erngb.build.inters, v)
}

func (erngb *EventReminderNotificationGroupBy) sqlScan(ctx context.Context, root *EventReminderNotificationQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(erngb.fns))
	for _, fn := range erngb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*erngb.flds)+len(erngb.fns))
		for _, f := range *erngb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*erngb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := erngb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// EventReminderNotificationSelect is the builder for selecting fields of EventReminderNotification entities.
type EventReminderNotificationSelect struct {
	*EventReminderNotificationQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (erns *EventReminderNotificationSelect) Aggregate(fns ...AggregateFunc) *EventReminderNotificationSelect {
	erns.fns = append(erns.fns, fns...)
	return erns
}

// Scan applies the selector query and scans the result into the given value.
func (erns *EventReminderNotificationSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, erns.ctx, "Select")
	if err := erns.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*EventReminderNotificationQuery, *EventReminderNotificationSelect](ctx, erns.EventReminderNotificationQuery, erns, erns.inters, v)
}

func (erns *EventReminderNotificationSelect) sqlScan(ctx context.Context, root *EventReminderNotificationQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(erns.fns))
	for _, fn := range erns.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*erns.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := erns.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
