// Code generated by ent, DO NOT EDIT.

package ent

import "context"

func (u *User) Friends(ctx context.Context) ([]*User, error) {
	result, err := u.Edges.FriendsOrErr()
	if IsNotLoaded(err) {
		result, err = u.QueryFriends().All(ctx)
	}
	return result, err
}

func (u *User) Followers(ctx context.Context) ([]*User, error) {
	result, err := u.Edges.FollowersOrErr()
	if IsNotLoaded(err) {
		result, err = u.QueryFollowers().All(ctx)
	}
	return result, err
}

func (u *User) Following(ctx context.Context) ([]*User, error) {
	result, err := u.Edges.FollowingOrErr()
	if IsNotLoaded(err) {
		result, err = u.QueryFollowing().All(ctx)
	}
	return result, err
}
