appEnv: prod

database:
  user: Happ_db_user
  password: Happ_db_password
  net: tcp
  addr: Happ_db_addr
  dbname: happ_dev
  allowNativePasswords: true
  params:
    parseTime: true
    charset: utf8mb4
    tls: true

meilisearchMK: meilisearchMK
firebaseSAPrivateKey: FirebaseSAPrivateKey
mapsAPIKey: MapsAPIKey