version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: happ_server
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - APP_ENV=prod
    restart: unless-stopped