version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: juanmartin8a/happ_server:v0.1.1
    ports:
      - "8080:8080"
    environment:
      - APP_ENV=prod
      - PORT=8080
    restart: unless-stopped