// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type User struct {
	ID        float64 `json:"id"`
	Name      string  `json:"name"`
	Birthday  string  `json:"birthday"`
	CreatedAt string  `json:"createdAt"`
	UpdatedAt string  `json:"updatedAt"`
}
